### Pandas Introduction

[Pandas Documentation](https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html)

In [1]:
import pandas as pd
import numpy as np

### Series

In [2]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a': 10,
     'b': 20,
     'c': 30}

In [3]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(data = my_data, index=labels) #Using specified parameters

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(my_data, labels) #Using ordinal position of parameters, no need to specify parameters if you place in proper order

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr) #NumPy array as argument to be passed in

0    10
1    20
2    30
dtype: int32

In [7]:
pd.Series(arr, labels) #Assigning labels with NumPy array

a    10
b    20
c    30
dtype: int32

In [8]:
pd.Series(d) #Using a dictionary, which assigns the keys as the index and values as the values

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [10]:
ser1 = pd.Series([1,2,3,4], ['USA', 'Germany', 'USSR', 'Japan'])
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [11]:
ser1['USA'] #Grabbing data point for the USA index, typing it as a string because we know USA is a string

1

In [12]:
ser2 = pd.Series([1,2,5,4], ['USA', 'Germany', 'Italy', 'Japan'])
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [13]:
ser3 = pd.Series(data = labels) #Grabbing information with integer index
ser3[0]

'a'

In [14]:
ser1 + ser2 #Adding the two series together, it tries to match it on the index, returns NaN

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

### DataFrames

In [15]:
from numpy.random import randn

In [16]:
np.random.seed(101)

In [17]:
df = pd.DataFrame(randn(5,4),['A', 'B', 'C','D','E'],['W','X','Y','Z'])
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

##### Selecting Columns

In [18]:
df['W'] #OR df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [19]:
df[['W','Z',]] #Selecting multiple columns

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [20]:
df['New'] = df['W'] + df['Y'] #Creating a new column
df

          W         X         Y         Z       New
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

##### Selecting Rows

In [21]:
df.loc['A'] #loc stands for location, and takes in a index label

W      2.706850
X      0.628133
Y      0.907969
Z      0.503826
New    3.614819
Name: A, dtype: float64

In [22]:
df.iloc[0] #iloc stands for index based location, and takes in a numerical index location

W      2.706850
X      0.628133
Y      0.907969
Z      0.503826
New    3.614819
Name: A, dtype: float64

##### Selecting Specific Values

In [23]:
df.loc['B','Y'] #Returning a value located at row, and column location (Row B, Column Y)

-0.8480769834036315

In [24]:
df.loc[['A', 'B'], ['W', 'Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

##### Dropping Columns

In [25]:
#Deleting a column, need to specify the axis = 1 for COLUMNS, defaults to axis = 0 which is for INDEX
#Syntax below does not edit DF inplace (meaning it only drops in this view, and does not edit the original DF)
#Use the inplace = True argument to accomplish this

df.drop('New', axis=1, inplace=True)
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

##### Dropping Rows

In [26]:
df.drop('E', axis=0) #Axis=0 is the default, so not necessary to specify in this case

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [27]:
df.shape #Checking the number of columns and rows (Also why rows are referred to as the 0 axis...(rows, columns))

(5, 4)

##### Conditional Selection

In [28]:
df > 0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [29]:
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [30]:
df['W'] > 0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [31]:
df[df['W'] > 0] #Since we are passing in a series, we no longer get the null values

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [32]:
df[df['Z'] < 0]

          W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [33]:
df[df['W']>0]['X'] #Return values for X column where W column is > 0

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [34]:
#Using and instead of & will result in an ambigous error, meaning that pandas/python gets confused
#when you try to pass more than one boolean value into the and comparison...use the pipe operator for OR...

df[(df['W']>0) & (df['Y']>1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [35]:
df.reset_index() #Resetting the index to a numerical value, getting rid of the alpha characters, inplace=True to fully overwrite

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [36]:
newind = 'CA NY WY OR CO'.split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [37]:
df['States'] = newind
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [38]:
df.set_index('States') #Assigning new index values based on the States columns we just created

               W         X         Y         Z
States
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

##### MultiIndex

In [39]:
#Index levels
outside = ['G1', 'G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [40]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])
df

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [41]:
df.loc['G1'] #call from outside index, and then contine to go deeper

          A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [42]:
df.loc['G1'].loc[1] #call from outside index, and then contine to go deeper

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [43]:
df.index.names = ['Groups','Num']
df

                   A         B
Groups Num
G1     1    0.302665  1.693723
       2   -1.706086 -1.159119
       3   -0.134841  0.390528
G2     1    0.166905  0.184502
       2    0.807706  0.072960
       3    0.638787  0.329646

In [44]:
df.loc['G1'].loc[2]['A']

-1.7060859307350775

In [45]:
df.loc['G1']

            A         B
Num
1    0.302665  1.693723
2   -1.706086 -1.159119
3   -0.134841  0.390528

In [46]:
#Cross Section for Multi Index...Grabbing values for Num index = 1 in G1 and G2
df.xs(1, level = 'Num')

               A         B
Groups
G1      0.302665  1.693723
G2      0.166905  0.184502

### Missing Data

In [47]:
d = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
df = pd.DataFrame(d)
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

##### Dropping

In [48]:
#If any rows have a null value, it drops it from the dataset. 

df.dropna() #Defaults to axis=0 which is rows

     A    B  C
0  1.0  5.0  1

In [49]:
df.dropna(axis = 1) #Defaults to axis=0 which is rows, use axis=1 for columns

   C
0  1
1  2
2  3

In [50]:
#thresh parameter can be used to keep specific rows/columns based on how many nulls there are. Threshold specified must be met
#to drop those rows/columns
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

##### Replacing

In [51]:
df.fillna(value='Fill VALUE')

            A           B  C
0         1.0         5.0  1
1         2.0  Fill VALUE  2
2  Fill VALUE  Fill VALUE  3

In [52]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

### Groupby

In [55]:
data = {'Company': ['Goog','Goog','MSFT','MSFT','FB','FB'],
        'Person': ['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
        'Sales': [200,120,340,124,243,350]}
companies_df = pd.DataFrame(data)
companies_df

  Company   Person  Sales
0    Goog      Sam    200
1    Goog  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [56]:
companies_df.groupby('Company') #Returns a groupby object

In [57]:
byCompany = companies_df.groupby('Company') #Assign the groupby object to a variable (still groupby object)
byCompany.mean() #Perform an aggregate function on the group

         Sales
Company
FB       296.5
Goog     160.0
MSFT     232.0

In [58]:
byCompany.sum()

         Sales
Company
FB         593
Goog       320
MSFT       464

In [59]:
companies_df.groupby('Company').sum().loc['FB']

Sales    593
Name: FB, dtype: int64

In [60]:
companies_df.groupby('Company').count()

         Person  Sales
Company
FB            2      2
Goog          2      2
MSFT          2      2

In [61]:
companies_df.groupby('Company').max()

          Person  Sales
Company
FB         Sarah    350
Goog         Sam    200
MSFT     Vanessa    340

In [62]:
companies_df.groupby('Company').describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
Goog      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0