### Pandas Introduction

[Pandas Documentation](https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html)

In [1]:
import pandas as pd
import numpy as np

### Series

In [2]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a': 10,
     'b': 20,
     'c': 30}

In [3]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(data = my_data, index=labels) #Using specified parameters

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(my_data, labels) #Using ordinal position of parameters, no need to specify parameters if you place in proper order

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr) #NumPy array as argument to be passed in

0    10
1    20
2    30
dtype: int32

In [7]:
pd.Series(arr, labels) #Assigning labels with NumPy array

a    10
b    20
c    30
dtype: int32

In [8]:
pd.Series(d) #Using a dictionary, which assigns the keys as the index and values as the values

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [10]:
ser1 = pd.Series([1,2,3,4], ['USA', 'Germany', 'USSR', 'Japan'])
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [11]:
ser1['USA'] #Grabbing data point for the USA index, typing it as a string because we know USA is a string

1

In [12]:
ser2 = pd.Series([1,2,5,4], ['USA', 'Germany', 'Italy', 'Japan'])
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [13]:
ser3 = pd.Series(data = labels) #Grabbing information with integer index
ser3[0]

'a'

In [14]:
ser1 + ser2 #Adding the two series together, it tries to match it on the index, returns NaN

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

### DataFrames

In [15]:
from numpy.random import randn

In [16]:
np.random.seed(101)

In [17]:
df = pd.DataFrame(randn(5,4),['A', 'B', 'C','D','E'],['W','X','Y','Z'])
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

##### Selecting Columns

In [18]:
df['W'] #OR df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [19]:
df[['W','Z',]] #Selecting multiple columns

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [20]:
df['New'] = df['W'] + df['Y'] #Creating a new column
df

          W         X         Y         Z       New
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

##### Selecting Rows

In [25]:
df.loc['A'] #loc stands for location, and takes in a index label

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [27]:
df.iloc[0] #iloc stands for index based location, and takes in a numerical index location

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

##### Selecting Specific Values

In [28]:
df.loc['B','Y'] #Returning a value located at row, and column location (Row B, Column Y)

-0.8480769834036315

In [29]:
df.loc[['A', 'B'], ['W', 'Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

##### Dropping Columns

In [21]:
#Deleting a column, need to specify the axis = 1 for COLUMNS, defaults to axis = 0 which is for INDEX
#Syntax below does not edit DF inplace (meaning it only drops in this view, and does not edit the original DF)
#Use the inplace = True argument to accomplish this

df.drop('New', axis=1, inplace=True)
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

##### Dropping Rows

In [22]:
df.drop('E', axis=0) #Axis=0 is the default, so not necessary to specify in this case

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [24]:
df.shape #Checking the number of columns and rows (Also why rows are referred to as the 0 axis...(rows, columns))

(5, 4)